name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest -q

  # Optional: try running the pipeline (comment out if flaky due to network)
  pipeline:
    needs: test
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pipeline
        env:
          # If needed, add Kaggle creds in repo Settings > Secrets and variables > Actions
          # KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          # KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
          PYTHONUNBUFFERED: "1"
        run: |
          mkdir -p data/raw data/bronze data/silver data/gold
          python src/pipeline.py
      - name: Upload DuckDB artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lakehouse-duckdb
          path: data/lakehouse.duckdb
          if-no-files-found: ignore
